project:
  type: website
  render:
    - index.md
    - presenters/*
    - exercises/*
    - slides/*
  execute-dir: project
  output-dir: docs
  resources:
    - assets/images/website-card.jpg
    - assets/library/bibliography.bib
    - assets/library/apa.csl
    - slides/intensive-longitudinal.pdf
    - slides/advanced-methods.pdf
website:
  title: "Sample Size Help"
  description: |
    In recent years the popularity of procedures to collect intensive
    longitudinal data such as the Experience Sampling Method has increased
    immensely. The goal of this workshop is to address this crucial question by
    presenting methodological advances for sample size planning for intensive
    longitudinal designs.
  site-url: "https://samplesize.help"
  twitter-card:
      title: "Sample Size Planning Workshop"
      description: |
        Methodological advances in sample size planning for intensive
        longitudinal designs.
      image: "/assets/images/website-card.jpg"
      site: https://samplesize.help
      card-style: summary
  navbar:
    left:
      - text: Home
        href: index.md
      - text: Slides
        menu:
          - href: slides/intensive-longitudinal.pdf
            text: "Sample size planning for intensive longitudinal designs"
          - href: slides/advanced-methods.pdf
            text: "Advanced methods for sample size planning"
      - text: Exercises
        menu:
          - href: exercises/power-simulation-n-1-intensive-designs.Rmd
            text: Simulation-based power for $N = 1$ intensive designs
          - href: exercises/sample-size-solutions-n-1-intensive-designs.Rmd
            text: Sample size solutions for $N = 1$ intensive designs
          - href: exercises/estimation-multilevel-leuven-clinical-data.Rmd
            text: Multilevel model estimation using the Leuven Clinical Dataset
          - href: exercises/power-multilevel-cross-level-interaction-intensive-designs.Rmd
            text: Power for multilevel cross-level interaction intensive designs
          - href: exercises/power-multilevel-ar-intensive-designs.Rmd
            text: Power for multilevel $\text{AR}(1)$ intensive designs
          - href: exercises/sample-size-analysis-powerly.qmd
            text: Sample size analysis using `powerly`
      - text: Presenters
        menu:
          - href: presenters/ginette-lafit.md
            text: Ginette Lafit
          - href: presenters/jordan-revol.md
            text: Jordan Revol
          - href: presenters/mihai-constantin.md
            text: Mihai Constantin
          - href: presenters/eva-ceulemans.md
            text: Eva Ceulemans
    tools:
      - icon: github
        menu:
          - text: Source code and materials
            url:  https://github.com/mihaiconstantin/sample-size-workshop
          - text: Report an issue
            url:  https://github.com/mihaiconstantin/sample-size-workshop/issues
format:
  html:
    embed-resources: true
    grid:
      body-width: 900px
    theme:
      light: cosmo
    css: assets/css/styles.css
    toc: false
bibliography: assets/library/bibliography.bib
csl: assets/library/apa.csl
