project:
  type: website
  render:
    - index.md
    - presenters/*
    - exercises/*
  execute-dir: project
  output-dir: docs
  resources:
    - assets/images/website-card.jpg
website:
  title: "Sample Size Help"
  description: |
    In recent years the popularity of procedures to collect intensive
    longitudinal data such as the Experience Sampling Method has increased
    immensely. The goal of this workshop is to address this crucial question by
    presenting methodological advances for sample size planning for intensive
    longitudinal designs.
  twitter-card:
      title: "Sample Size Planning Workshop"
      description: |
        Methodological advances in sample size planning for intensive
        longitudinal designs.
      image: /assets/images/website-card.jpg
      site: https://samplesize.help
  navbar:
    left:
      - text: Home
        href: index.md
      - text: Slides
        menu:
          - href: slide.md
            text: The First Set of Slides
      - text: Exercises
        menu:
          - href: exercises/power-analysis-var-1.Rmd
            text: Simulation-based power for $\text{AR}(1)$ and $\text{VAR}(1)$
          - href: exercises/sample-size-solutions-n-1.Rmd
            text: Sample size solutions for $N = 1$ intensive designs
          - href: exercises/sample-size-analysis-ggm.md
            text: Sample size analysis for the $\text{GGM}$
          - href: exercise.md
            text: "..."
      - text: Presenters
        menu:
          - href: presenters/ginette-lafit.md
            text: Ginette Lafit
          - href: presenters/jordan-revol.md
            text: Jordan Revol
          - href: presenters/mihai-constantin.md
            text: Mihai Constantin
          - href: presenters/eva-ceulemans.md
            text: Eva Ceulemans
    tools:
      - icon: github
        menu:
          - text: Source code and materials
            url:  https://github.com/mihaiconstantin/sample-size-workshop
          - text: Report an issue
            url:  https://github.com/mihaiconstantin/sample-size-workshop/issues
format:
  html:
    embed-resources: true
    grid:
      body-width: 900px
    theme:
      light: cosmo
    css: assets/css/styles.css
    toc: false
